# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title-bold: For Students
title-normal: Machine Learning
email: 
description: 괄호에 있는 순서를 따라 진행해주세요. Anaconda 설치 필수! MENU에 Directory가 저장되어 있습니다.
baseurl: "/Machine-for-Learning-Site" # the subpath of your site, e.g. /blog
url: "https://waylight3.github.io" # the base hostname & protocol for your site
author: ghk829&waylight3
street_address: 
city: 매일 행복하진 않지만
state: 행복한 일은 매일 있어
zip_code: 
country:
phone: 

# Plugins
gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jemoji

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages" 
tiles-count: 100

# Social settings
500px_url: 
facebook_url: https://facebook.com
github_url: 
gitlab_url: https://gitlab.com/u/andrewbanchich
googleplus_url: 
instagram_url: https://instagram.com
linkedin_url: 
pinterest_url: 
slack_url: 
twitter_url: 

# Build settings
markdown: kramdown

# Plugin: jekyll-seo-tag
twitter:
  username: andrewbanchich
# Add one or more of the following
facebook:
  app_id: 
  publisher: 
  admins: 
logo:
google_site_verification: 
